// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWovzTZW5D5Ma8c-oCoXFEJz84G3yLqwI',
    appId: '1:974569926830:web:0da89fde58bda4e8d23d3f',
    messagingSenderId: '974569926830',
    projectId: 'd-ola-cb33f',
    authDomain: 'd-ola-cb33f.firebaseapp.com',
    storageBucket: 'd-ola-cb33f.appspot.com',
    measurementId: 'G-VZVPED3GLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2mJIiRWY-2Gz4Q_z2dZ_XgaoPK-MSO2c',
    appId: '1:974569926830:android:44a9fec08d8c2a73d23d3f',
    messagingSenderId: '974569926830',
    projectId: 'd-ola-cb33f',
    storageBucket: 'd-ola-cb33f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgxIDkrWWfjHJzjyhBnP7cm_SoC9keWn4',
    appId: '1:974569926830:ios:2a9a0feb8dc9babad23d3f',
    messagingSenderId: '974569926830',
    projectId: 'd-ola-cb33f',
    storageBucket: 'd-ola-cb33f.appspot.com',
    iosClientId: '974569926830-3lo266vhg9ul7h2apudn3u8mopv0mqo4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapboxTurnByTurn',
  );
}
